

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3)# G = graphs.CompleteGraph(9)
# G.delete_edge(0,1)
# print(G.chromatic_polynomial().factor())

# print(
# G.degree(),
# G.class()
# )

G = graphs.Connected(_sage_const_3 )
print(G.chromatic_index(), max(G.degree()))
plot(G)
show()
G.plot()

